### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by Jungorend** [pmonks/spinner#10]
## Support Question

Right now the workflow for deploying this library locally could potentially be detailed a bit more.
Looking at the deps.edn we see various aliases are mentioned in order to make use of the test and similar, however these are only present in the main branch. The dev branch is considerably more trimmed down, and similar commands will not work.

As the dev branch is the intended one for any pull requests, it would be useful to provide documentation on setting up and running this library within the dev branch.

**Comment by pmonks** [comment]
Fixed in rev 39a6c3033aae1bcf6594b191ca2e186fc81d2a59.
